# Generated by Django 3.2.6 on 2021-12-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0003_alter_cliente_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('decris', models.TextField(max_length=400)),
                ('price', models.CharField(max_length=20)),
            ],
        ),
    ]
